### ISSUE TITLE
Exception when loading h5wasm as ES module from another ES module

### ISSUE THREAD

**Issue by rsemenov100** [usnistgov/h5wasm#17]
Hi,

We have a CommonJS module that depends on 'h5wasm'. Everything works fine.

I converted our module from CommonJS to ESM and got an exception when 'h5wasm' is loaded.

To simplify everything, I created a brand new little ES module that has nothing but one unit test, which tries to open a file. Got exactly the same exception:

```
$ mocha --recursive --loader=ts-node/esm -R spec "src/**/*.spec.ts" --no-timeouts --exit
(node:94962) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:94962) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

/Users/rsemenov/vsts/test-h5wasm/node_modules/h5wasm/dist/esm/hdf5_hl.js:1
import { default as ModuleFactory } from './hdf5_util.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/Users/rsemenov/vsts/test-h5wasm/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/rsemenov/vsts/test-h5wasm/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/Users/rsemenov/vsts/test-h5wasm/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/rsemenov/vsts/test-h5wasm/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/rsemenov/vsts/test-h5wasm/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
``` 

I followed the warning in the log above:
```
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```
and added this line:
```
"type": "module",
```
to
```
/Users/rsemenov/vsts/test-h5wasm/node_modules/h5wasm/package.json
```

After this, exception disappeared.

I'm not sure why 'h5wasm' doesn't have the 'type' property specified in its package.json. If I remember correctly, unless it's explicitly set to 'module', it is assumed that the module is CommonJS.

I'm using Node.js v16.14.0 and TypeScript. The 'target' and 'module' properties in tsconfig.ts:
```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "es2020",
    "moduleResolution": "node",
```

Best regards,
Roman

**Comment by bmaranville** [comment]
I have been having trouble figuring out the best way to include both the commonjs version (for node) and ESM (web) version of this library with a single package.json.  If I put ```"type": "module"``` in the package.json it will break for people using the commonjs version of the library.  I have considered converting the nodejs build to ESM as well, since ESM support in node is pretty good now.

**Comment by bmaranville** [comment]
There is an important difference between the commonjs and the ESM modules as well:
 - ESM version is compiled with MEMFS and IDBFS (for the web)
 - CJS version is compiled with NODERAWFS for direct filesystem access in node

@rsemenov100 - are you targeting node, and do you want direct filesystem access?

**Comment by rsemenov100** [comment]
I'm targeting node and direct filesystem access.

**Comment by bmaranville** [comment]
I think I will convert to ESM for both versions of the compiled library, but still users will have to take care when importing.  I will probably make the MEMFS version the default import, and then users wanting NODERAWFS will have to import e.g. 'h5wasm/noderawfs' to get direct filesystem access

**Comment by bmaranville** [comment]
I ended up indicating the node import directly in the imports section of package.json...  hopefully will work for everyone.  If you want MEMFS in node you can override by importing directly from ```./dist/esm/hdf5_hl.js``` but everyone else should get what they want with just ```import h5wasm from "h5wasm";```
```json
  "exports": {
    "node": "./dist/node/hdf5_hl.js",
    "import": "./dist/esm/hdf5_hl.js"
  },
```

**Comment by bmaranville** [comment]
I am hoping your issue is addressed in the new release [v0.4.0](https://github.com/usnistgov/h5wasm/releases/tag/v0.4.0)

**Comment by rsemenov100** [comment]
Yes, I don't see exception anymore. Thank you so much!
