### ISSUE TITLE
TypeError: wasm function signature contains illegal type, in a Qt WebEngine

### ISSUE THREAD

**Issue by cavenel** [usnistgov/h5wasm#41]
I am trying to use h5wasm from an html page displayed in a Qt WebEngine in a Qt application.
The Qt WebEngine is using Chromium (v87), with the V8 javascript engine (see https://wiki.qt.io/QtWebEngine for more info).

The code runs fine outside of Qt, but within Qt I get a similar error as https://github.com/emscripten-core/emsdk/issues/476:
```javascript
Uncaught (in promise) TypeError: wasm function signature contains illegal type
    at embind_init_builtin() (<anonymous>:wasm-function[4431]:0x2cceb2)
    at _GLOBAL__sub_I_bind.cpp (<anonymous>:wasm-function[4432]:0x2cd0db)
    at __wasm_call_ctors (<anonymous>:wasm-function[67]:0x4923)
    at callRuntimeCallbacks (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:1192:26)
    at initRuntime (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:796:3)
    at doRun (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:7972:5)
    at run (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:7992:5)
    at runCaller (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:7933:19)
    at removeRunDependency (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:921:7)
    at receiveInstance (http://127.0.0.1:5432/static/vendor/h5wasm/hdf5_util.js:1082:5)
```

I checked and BigInt are included in javascript from the Qt Webengine (which is expected, as it is using V8 on Chromium v87):
![image](https://user-images.githubusercontent.com/6164758/203990903-9fadd9d7-0151-4086-964c-cfcc1d0cce68.png)

I also checked that the js file was compiled with `-s WASM_BIGINT`, and even compiled it myself to be sure.

I tried to run Qt with additional options: `--wasm-staging`, `--enable-experimental-webassembly-features`, `enable-webassembly-baseline`, but nothing worked and I am now out of ideas.

(I am not 100% sure if this repo is the best place to ask this, or the emsdk repo, or the Qt repo. But it seems to be a wasm issue from what I understand.)

**Comment by cavenel** [comment]
In the end I upgraded to Qt6, which apparently has a better support of wasm, and it works. I guess it was just compatibility issues between Qt and Wasm, nothing to do with h5wasm!

**Comment by bmaranville** [comment]
Great!  That's very useful information!
